#!/bin/bash

echo Current frequency is
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

echo -e "Integer Test:\n"
gcc ./integer_test.c
time ./a.out
echo -e '\n'

echo -e "Float Test:\n"
gcc ./float_test.c
time ./a.out
echo -e "\n"
